// Equation cross-references for KaTeX math.
//
// KaTeX has no \label/\ref: it renders each formula in isolation and never
// tracks numbers across a document, so LaTeX's cross-reference machinery does
// not exist here. What it DOES have is automatic numbering — an unstarred
// environment (`align`, `equation`) emits <span class="eqn-num">, and
// katex.min.css prints the number from a CSS counter:
//
//   .eqn-num:before { content: "(" counter(katexEqnNo) ")"; counter-increment: katexEqnNo }
//
// The number therefore exists ONLY at render time, in CSS — it is nowhere in the
// HTML for a plugin to read. So this plugin recomputes it: it walks the numbered
// display equations in document order (the same order, and the same skip rules,
// the CSS counter uses) and fills each reference link's text with the count it
// arrived at. The invariant to preserve is that this walk must increment on
// exactly the equations katexEqnNo increments on — i.e. those with an .eqn-num
// span — or numbers and references will silently disagree.
//
// Authoring contract:
//   define    $$\begin{align} \htmlId{eq:foo}{ ... } \end{align}$$
//   reference [](#eq:foo)      → renders as "(2)", linked
//
// \htmlId is used rather than a stray <div id> because it lives INSIDE the math,
// where MDX never sees its braces. A bare \ref{...} in MDX prose is parsed as a
// JSX expression and hard-fails the build with "Unexpected content after
// expression" — that trap is the reason this indirection exists.
//
// Requires rehype-katex to run FIRST (this reads its output) and to be
// configured with `trust: true`, which is what enables \htmlId.

import { visit } from 'unist-util-visit';

const hasClass = (node, name) => {
	const cls = node.properties?.className;
	return Array.isArray(cls) ? cls.includes(name) : cls === name;
};

/** Depth-first search for the first descendant matching `test`. */
function find(node, test) {
	let hit = null;
	visit(node, (n) => {
		if (hit) return false;
		if (test(n)) {
			hit = n;
			return false;
		}
	});
	return hit;
}

export default function rehypeEqref() {
	return (tree) => {
		// Pass 1 — walk display-math blocks IN DOCUMENT ORDER, which is the order
		// the CSS counter increments in. Only unstarred environments carry an
		// .eqn-num span, and only those advance katexEqnNo, so numbering here must
		// count exactly those and skip align*/aligned.
		const numberOf = new Map(); // id -> equation number
		let n = 0;

		visit(tree, 'element', (node) => {
			if (!hasClass(node, 'katex-display')) return;

			const numbered = find(node, (d) => d.type === 'element' && hasClass(d, 'eqn-num'));
			if (!numbered) return; // starred env: no number, no counter bump
			n += 1;

			// The id comes from \htmlId inside the math. KaTeX renders that id on an
			// inner span; hoist it to the display wrapper so the anchor lands on the
			// whole equation (and scroll-margin can clear the sticky navbar).
			const labelled = find(node, (d) => d.type === 'element' && d.properties?.id);
			if (!labelled) return;

			const id = String(labelled.properties.id);
			delete labelled.properties.id;
			node.properties = node.properties || {};
			node.properties.id = id;
			numberOf.set(id, n);
		});

		if (numberOf.size === 0) return;

		// Pass 2 — turn <a href="#eq:foo"> into a counter-driven reference. The link
		// text is generated by CSS (see global.css .eqref:before), not written here,
		// so it cannot drift from the equation's own number.
		visit(tree, 'element', (node) => {
			if (node.tagName !== 'a') return;
			const href = node.properties?.href;
			if (typeof href !== 'string' || !href.startsWith('#')) return;

			const num = numberOf.get(href.slice(1));
			if (num === undefined) return;

			const cls = node.properties.className;
			node.properties.className = Array.isArray(cls) ? [...cls, 'eqref'] : ['eqref'];
			// Keep equation jumps out of the back/forward stack.
			// A local preventDefault() is NOT enough: ClientRouter runs its own
			// delegated click listener, sees a same-page `#hash` link, and calls
			// pushState via moveToLocation() — so every reference click added a
			// history entry and Back walked through them one by one. ClientRouter
			// reads this attribute (ClientRouter.astro: dataset.astroHistory) and
			// then replaces instead of pushing.
			node.properties['data-astro-history'] = 'replace';
			// Empty link text ([](#eq:foo)) → fill in "(2)". An author who wrote their
			// own text ("the frame equation") keeps it. The number is emitted as real
			// text rather than CSS content so it survives copy/paste and CSS-off.
			if (node.children.length === 0) {
				node.children = [{ type: 'text', value: `(${num})` }];
			}
		});
	};
}
